In [147]:
import numpy as np
import pandas as pd
from matplotlib.pyplot import subplots
import sklearn

In [148]:
import os

In [149]:
os.getcwd()

'c:\\Users\\carle\\Documents\\Cognitive_Science\\MASTER\\Data science\\Data science exam'

In [150]:
gini = pd.read_csv('data/gini.csv', index_col=0, skiprows=3)
gdp = pd.read_csv('data/gdp.csv', index_col=0, skiprows=3)
inflation = pd.read_csv('data/inflation.csv', index_col=0, skiprows=3)
unemployment = pd.read_csv('data/unemployment.csv', index_col=0, skiprows=3)

In [151]:
gini.head()

,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,1966,...,2017,2018,2019,2020,2021,2022,2023,2024,2025,Unnamed: 70
Country Name,,,,,,,,,,,,,,,,,,,,,
Aruba,ABW,Gini index,SI.POV.GINI,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Africa Eastern and Southern,AFE,Gini index,SI.POV.GINI,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Afghanistan,AFG,Gini index,SI.POV.GINI,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Africa Western and Central,AFW,Gini index,SI.POV.GINI,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Angola,AGO,Gini index,SI.POV.GINI,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,51.3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [152]:
gdp.head()

,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,1966,...,2017,2018,2019,2020,2021,2022,2023,2024,2025,Unnamed: 70
Country Name,,,,,,,,,,,,,,,,,,,,,
Aruba,ABW,GDP per capita growth (annual %),NY.GDP.PCAP.KD.ZG,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,3.485815,3.048518,0.951664,-23.466273,15.675519,11.038520,7.657640,6.181751,NaN,NaN
Africa Eastern and Southern,AFE,GDP per capita growth (annual %),NY.GDP.PCAP.KD.ZG,NaN,-2.182395,5.075379,2.795642,1.790384,2.225029,1.922442,...,0.000238,-0.064991,-0.709407,-5.405934,1.844404,1.068005,-0.604582,0.253854,NaN,NaN
Afghanistan,AFG,GDP per capita growth (annual %),NY.GDP.PCAP.KD.ZG,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,-0.195570,-1.713743,0.856295,-5.382515,-22.584482,-7.576669,0.106093,NaN,NaN,NaN
Africa Western and Central,AFW,GDP per capita growth (annual %),NY.GDP.PCAP.KD.ZG,NaN,-0.251185,1.538542,4.740660,3.086962,1.823450,-3.703529,...,-0.355283,0.330202,0.792058,-6.003416,0.154018,2.064401,1.218110,2.107058,NaN,NaN
Angola,AGO,GDP per capita growth (annual %),NY.GDP.PCAP.KD.ZG,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,-3.622865,-3.968525,-3.529000,-7.127615,-1.094341,0.991407,-1.808703,1.292933,NaN,NaN

In [153]:
gini, gdp, inflation, unemployment = [
    df.loc[['United States']]
    for df in [gini, gdp, inflation, unemployment]
]

In [154]:
gini, gdp, inflation, unemployment = [
    df.drop(columns=["Country Code", "Indicator Name", "Indicator Code", "Unnamed: 70"])
    for df in [gini, gdp, inflation, unemployment]
]

In [158]:
gini, gdp, inflation, unemployment = [
    df.melt(var_name="year", value_name=name)
    for df, name in zip(
        [gini, gdp, inflation, unemployment],
        ["gini", "gdp", "inflation", "unemployment"]
    )
]

In [159]:
gini['year'], gdp['year'], inflation['year'], unemployment['year'] = [
    df["year"].astype(int)
    for df in [gini, gdp, inflation, unemployment]
]

ValueError: invalid literal for int() with base 10: 'year'

In [ ]:
gini = gini.drop(columns=["Country Name", "Country Code", "Indicator Name", "Indicator Code", "Unnamed: 70"])

In [160]:
gdp

                                                  year          gdp
0                                                 year  1960.000000
1                                                 year  1961.000000
2                                                 year  1962.000000
3                                                 year  1963.000000
4                                                 year  1964.000000
..                                                 ...          ...
127                 1960      1961      1962      1...     5.888341
128                 1960      1961      1962      1...     1.923862
129                 1960      1961      1962      1...     2.035600
130                 1960      1961      1962      1...     1.794192
131                 1960      1961      1962      1...          NaN

[132 rows x 2 columns]

In [ ]:
gini_long

    year  gini
0   1960   NaN
1   1961   NaN
2   1962   NaN
3   1963  36.7
4   1964  37.4
..   ...   ...
61  2021  39.7
62  2022  41.7
63  2023  41.8
64  2024  41.8
65  2025   NaN

[66 rows x 2 columns]

In [ ]:
election_results = pd.read_csv('data/election_results.csv')

In [ ]:
election_results.head()

,year,prospective conscutive term for incumbent party,prospective 1st/2nd term for incumbent party candidate,incumbent party,popular vote for incumbent party,popular vote for non-incumbent party,winner party,winner president,loser
0,2024,1,1,Democratic,48.34,49.81,Republican,Donald Trump,Kamala Harris
1,2020,1,1,Republican,46.86,51.31,Democratic,Joe Biden,Donald Trump
2,2016,3,1,Democratic,48.20,46.20,Republican,Donald Trump,Hillary Clinton
3,2012,2,2,Democratic,51.10,47.20,Democratic,Barack Obama,Mitt Romney
4,2008,3,1,Republican,45.70,52.90,Democratic,Barack Obama,John McCain

In [ ]:
print(gini_long["year"].dtype) 
gini_long["year"] = gini_long["year"].astype(int)

int64

In [142]:
prediction_data = pd.merge(election_results, gini, how = 'left', on=['year'])

In [143]:
prediction_data = pd.merge(prediction_data, gdp, how = 'left', on=['year'])

In [144]:
prediction_data = pd.merge(prediction_data, unemployment, how = 'left', on=['year'])

In [145]:
prediction_data = pd.merge(prediction_data, inflation, how = 'left', on=['year'])

MergeError: Passing 'suffixes' which cause duplicate columns {'df_x'} is not allowed.

In [ ]:
prediction_data = prediction_data.dropna()

In [146]:
prediction_data

,year,prospective conscutive term for incumbent party,prospective 1st/2nd term for incumbent party candidate,incumbent party,popular vote for incumbent party,popular vote for non-incumbent party,winner party,winner president,loser,df_x,df_y,df
0,2024,1,1,Democratic,48.34,49.81,Republican,Donald Trump,Kamala Harris,41.8,1.794192,4.022
1,2020,1,1,Republican,46.86,51.31,Democratic,Joe Biden,Donald Trump,40.0,-2.561807,8.055
2,2016,3,1,Democratic,48.20,46.20,Republican,Donald Trump,Hillary Clinton,41.3,1.022666,4.869
3,2012,2,2,Democratic,51.10,47.20,Democratic,Barack Obama,Mitt Romney,41.2,1.475706,8.069
4,2008,3,1,Republican,45.70,52.90,Democratic,Barack Obama,John McCain,41.1,-0.828888,5.784
5,2004,2,2,Republican,50.70,48.30,Republican,George W. Bush,John Kerry,40.5,2.891111,5.529
6,2000,3,1,Democratic,48.40,47.90,Republican,George W. Bush,Al Gore,40.1,2.925863,3.992
7,1996,2,2,Democratic,49.20,40.70,Democratic,Bill Clinton,Bob Dole,40.3,2.572464,5.451
8,1992,4,2,Republican,37.40,43.00,Democratic,Bill Clinton,George H. W. Bush,38.4,2.096669,7.500
9,1988,3,1,Republican,53.60,45.60,Republican,George H. W. Bush,Michael Dukakis,37.7,3.235338,NaN
10,1984,2,2,Republican,58.80,40.60,Republican,Ronald Reagan,Walter Mondale,37.3,6.311989,NaN
11,1980,2,2,Democratic,41.00,50.70,Republican,Ronald Reagan,Jimmy Carter,34.7,-1.209324,NaN
12,1976,3,1,Republican,48.00,50.10,Democratic,Jimmy Carter,Gerald R. Ford,35.6,4.391358,NaN
13,1972,2,1,Republican,60.70,37.50,Republican,Richard Nixon,George McGovern,36.7,4.134728,NaN
14,1968,3,1,Democratic,42.70,43.40,Republican,Richard Nixon,Hubert Humphrey,36.3,3.758819,NaN
15,1964,2,1,Democratic,61.10,38.50,Democratic,Lyndon B. Johnson,Barry Goldwater,37.4,4.340549,NaN
16,1960,3,1,Republican,49.50,49.70,Democratic,John F. Kennedy,Richard Nixon,NaN,NaN,NaN

In [ ]:
import statsmodels.api as sm

In [ ]:
from ISLP import load_data
from ISLP.models import (ModelSpec as MS ,
summarize ,
poly)

In [ ]:
X = prediction_data[['gini']]

In [ ]:
y = prediction_data['popular vote for incumbent party']
model = sm.OLS(y, X)
results = model.fit()

In [ ]:
summarize(results)

c:\Users\carle\AppData\Local\Programs\Python\Python310\lib\site-packages\scipy\stats\_axis_nan_policy.py:418: UserWarning: `kurtosistest` p-value may be inaccurate with fewer than 20 observations; only n=16 observations were given.
  return hypotest_fun_in(*args, **kwds)

        coef  std err       t  P>|t|
gini  1.2717    0.047  26.793    0.0